[build]
  publish = "dist"
  functions = ".netlify/functions/"
[[redirects]]
  from = "/proxy-shit/*"
  to = ".netlify/functions/:splat"
  status = 200
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
